=== Yousuff-GIT/Web-Technologies-and-Internet-Programming/Exercise_19_Instant_Login_Feedback_and_Auto_Complete_using_Ajax/CitySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XSD schema defining structure of TamilNadu city list -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TamilNadu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="City" minOccurs="5" maxOccurs="25">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Name"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Yousuff-GIT/Web-Technologies-and-Internet-Programming/Exercise_19_Instant_Login_Feedback_and_Auto_Complete_using_Ajax/CityList.xml
<?xml version="1.0" encoding="UTF-8"?>
<TamilNadu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CitySchema.xsd">
  <City><Name>chennai</Name></City>
  <City><Name>chitambaram</Name></City>
  <City><Name>madurai</Name></City>
  <City><Name>mayavaram</Name></City>
  <City><Name>coimbatore</Name></City>
  <City><Name>trichy</Name></City>
  <City><Name>tutocorin</Name></City>
  <City><Name>salem</Name></City>
  <City><Name>villupuram</Name></City>
  <City><Name>vellore</Name></City>
  <City><Name>Dharmapuri</Name></City>
  <City><Name>Dindigul</Name></City>
  <City><Name>Kanyakumari</Name></City>
  <City><Name>Nagapattinam</Name></City>
  <City><Name>Namakkal</Name></City>
  <City><Name>Kanchipuram</Name></City>
</TamilNadu>
